// Type declarations for static asset imports (images, SVGs, fonts)
// next-env.d.ts is auto-generated by Next.js at runtime; this file
// covers the same ground so `tsc --noEmit` works without running the dev server.

declare module '*.webp' {
  const content: import('next/dist/client/image-component').StaticImageData
  export default content
}

declare module '*.png' {
  const content: import('next/dist/client/image-component').StaticImageData
  export default content
}

declare module '*.jpg' {
  const content: import('next/dist/client/image-component').StaticImageData
  export default content
}

declare module '*.jpeg' {
  const content: import('next/dist/client/image-component').StaticImageData
  export default content
}

declare module '*.gif' {
  const content: import('next/dist/client/image-component').StaticImageData
  export default content
}

declare module '*.svg' {
  const content: import('next/dist/client/image-component').StaticImageData
  export default content
}
